version: "3.9"

services:
  app:
    image: golang:latest
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
